language: node_js

cache:
  directories: node_modules

node_js:
- '6'

script:
- yarn test

notifications:
  slack:
    secure: OkvTx61AUUWuFZGurscM+Q/96CMZi0N+Dv+g86aRmVP5/jnp78ec0qimW1qiG5LE+TC7z/eAatG6PLD37tfCoCK2Ji2JwYUOpQmA3xZDMIcyzIzzmnkVB1njNHR6Z/Z0s/6ofsPKcU2vzhrbsbrSEKa66Ugs33qIoOwXwCZfQu2QDNuI7lU/7RWMDmtKedR08xrjP/g/tcba5ToUItk3LkGeXN4XHS/2zoxMf5HtepCuJLXqud+lcbHzEi9c0d2J3EH2B0184do9A+ogSaGGpU4LzF1UctMiFGl6wCKJGvX6uXGt3TV0kjqcFik69MAUJ9/Cmmcestna9/fv4vZPqL1xRvi32/OJZgk6JkP2gaXDg4ODxfBvch9RMrOMjivaY/BBiroR937FOtuc88TuLPvg5o9ajDVRA6pBI03GJXCkFkptcGSPmXlU537JbxQwuoxVD1K8S/kTbTkp852QhZh9HqdQPH0kz7QWSSL4ezgAz2wBICW80XMbEUTLv2nH7/YAFZqTYFGNRJnPtq5IJNiuJ/diaBSZNflUA8yBR+Mw9Rjm1Ycl45gzzN6tgydcM/biqrjvU9KYaSy3nuGoQEGG5x0Veqt91Zy/NUS8F5NBsSrCf1Oghp+DUNmGny6ewA9iQYERnC2lpynAQBzOOn9OKT4c4nFJaY9W8sKauDA=

before_deploy: yarn run dist
deploy:
- provider: gcs
  access_key_id: GOOGI5XWS6XGP254IWJC
  secret_access_key:
    secure: SKQ97hGbvqTUKoDOTzS1vCnDb/LM6fQGhWU1t7lLr0t5ejxdmat8XNFWDWO5gj+9pryNv/008aAP77nz9QEtZgJgyxBvCO7RQpMIBQu53U+dF3X9e75LFgUZY1NEKSq9VmxINldsGjIZrbLzDa9NCKW5sinENF8RkVsiYjo+EKMspJSPttR1y1W/M6BLx/wPyuR0sqBSuDu0w83mVvisKS7KyHXqHRG2sP7mlWz229vsSucG7qz+aBW1ZHOawDN+bwsD1AjvA2qDNIggMnwnvYd6e7lyUsP6/8Yl0UPFJmQX5yf+AMa/HioB5uIIJPEybJZk04KMbzjqToh+3/2bHyPEDllyNsIZxzESipI4vhTV0WCQ8LyzV6Skyzfbt00gjhnUGPVxIKjgCKXhN9g6GUAyfxJ7XpbweyGrhdBQiNNtet/7uqsKHIzvTVeqEQjmyqkWjaTwQ9xShcmi/jkznefatPvbQu9Ps+z/Bh2tQq05egmtLYif9ajN2aoFq6LSS6Gy1S1vxZtYmgI1nGpzrdUeLXONePB44Xt/OKJ8xAjdQZYDd4ocAU4Lg8XyCpP7Elytos/oVwqLRCPrIPrJ40DaCFxPgogXZe6sv0gUArObwlMMIjmy6XNbzPwX23BxCJ5MN+cAgCz75SzOOTg36QjdYW7SWZ/+CsZCzls8txc=
  bucket: floq-test
  local-dir: build
  upload-dir: overtime
  skip-cleanup: true
  acl: public-read
  cache_control: "max-age=0"
  on:
    repo: blankoslo/floq-overtime
    branch: develop
- provider: gcs
  access_key_id: GOOGI5XWS6XGP254IWJC
  secret_access_key:
    secure: SKQ97hGbvqTUKoDOTzS1vCnDb/LM6fQGhWU1t7lLr0t5ejxdmat8XNFWDWO5gj+9pryNv/008aAP77nz9QEtZgJgyxBvCO7RQpMIBQu53U+dF3X9e75LFgUZY1NEKSq9VmxINldsGjIZrbLzDa9NCKW5sinENF8RkVsiYjo+EKMspJSPttR1y1W/M6BLx/wPyuR0sqBSuDu0w83mVvisKS7KyHXqHRG2sP7mlWz229vsSucG7qz+aBW1ZHOawDN+bwsD1AjvA2qDNIggMnwnvYd6e7lyUsP6/8Yl0UPFJmQX5yf+AMa/HioB5uIIJPEybJZk04KMbzjqToh+3/2bHyPEDllyNsIZxzESipI4vhTV0WCQ8LyzV6Skyzfbt00gjhnUGPVxIKjgCKXhN9g6GUAyfxJ7XpbweyGrhdBQiNNtet/7uqsKHIzvTVeqEQjmyqkWjaTwQ9xShcmi/jkznefatPvbQu9Ps+z/Bh2tQq05egmtLYif9ajN2aoFq6LSS6Gy1S1vxZtYmgI1nGpzrdUeLXONePB44Xt/OKJ8xAjdQZYDd4ocAU4Lg8XyCpP7Elytos/oVwqLRCPrIPrJ40DaCFxPgogXZe6sv0gUArObwlMMIjmy6XNbzPwX23BxCJ5MN+cAgCz75SzOOTg36QjdYW7SWZ/+CsZCzls8txc=
  bucket: floq
  local-dir: build
  upload-dir: overtime
  skip-cleanup: true
  acl: public-read
  cache_control: "max-age=0"
  on:
    repo: blankoslo/floq-overtime
    branch: master
